require("colorscheme")
require("default")
require("fzf")
require("formatter")
require("git")
require("lsp")
require("nvimtree")
-- require("neotree")
require("statusline")
-- require("supermaven")
require("_tmux")
-- require("explore")
