require('colorscheme')
require("default")
require("fzf")
require('formatter')
require('git')
require('lsp')
require("nvimtree")
require('statusline')
-- require('supermaven')
require('_tmux')
require('treesitter')

